"""Pavement-derived taxi spine — medial-axis skeleton of ``pav_union``.

Painted-centerline and apt.dat route data are inconsistent across airports and
scenery packages (missing on small airports, absent on minor taxiways, encoded
differently per package).  The grading model, however, only *needs* a smooth,
unbroken spine through the paved area.  This module infers that spine from the
one input every airport has: the pavement footprint itself.

Method (classic Voronoi medial axis + graph fairing):

1. Sample the boundary (exterior + holes) of every pavement polygon at
   ``boundary_step`` metres and build the point Voronoi diagram (scipy/Qhull).
   Voronoi ridges whose endpoints both lie strictly inside the polygon
   approximate the medial axis; each skeleton vertex carries its CLEARANCE
   RADIUS (distance to the nearest boundary sample = local half-width).
2. Ridges generated by two *adjacent* boundary samples are perpendicular
   boundary noise, not axis — dropped up front.
3. PRUNE: iteratively remove leaf branches shorter than ``prune_factor`` x the
   clearance radius at their attachment node.  A boundary-bump whisker is
   always shorter than the local half-width; a genuine dead-end taxi stub is
   many times longer.  Iterate to a fixed point so nested whiskers collapse.
4. Collapse degree-2 runs into CHAINS between junction (deg >= 3) and leaf
   nodes, then fair each chain with an endpoint-pinned smoothing spline
   (junction welds survive smoothing).  A smoothed chain must stay inside the
   pavement; on failure the smoothing is halved until it fits (raw chain as
   the final fallback).
5. Optionally EXTEND leaf tips along their end tangent to the pavement
   boundary, so dead-end stubs and runway-edge contacts are covered end to
   end (the medial axis proper stops half a width short of an end cap).

Output chains form one topologically welded network per pavement piece:
chains meet exactly at shared junction endpoints — the "accurate, unbroken
spine" the curve-native slice model needs, with no dependency on painted
lines or apt.dat routes.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np
import networkx as nx
import shapely
from scipy.spatial import Voronoi, cKDTree
from scipy.interpolate import splprep, splev
from shapely.geometry import LineString, MultiPolygon, Point, Polygon
from shapely.ops import unary_union

# Boundary sampling step.  2 m resolves ~4 m-wide service lanes while keeping
# SPJC-sized airports at ~50k Voronoi sites (well under a second in Qhull).
_BOUNDARY_STEP_M = 2.0
# Skeleton vertices closer than this to the boundary are hairline artifacts
# (polygon corners generate zero-clearance vertices), never taxi surface.
_MIN_HALF_WIDTH_M = 1.0
# A leaf branch shorter than this multiple of its attachment node's clearance
# radius is boundary noise; a real stub is several radii long.
_PRUNE_FACTOR = 1.3
# Ignore pavement fragments below this area (paint slivers, debris).
_MIN_PIECE_AREA_M2 = 60.0
# Spline sampling step along a faired chain.
_CHAIN_STEP_M = 5.0
# Smoothing spline condition: s = (sigma per metre) * chain length.  Sigma is
# squared-residual budget per metre of chain, so smoothing scales with length.
_SMOOTH_SIGMA = 0.6
# Containment test allowance: the faired chain may leave the polygon by this
# much (grid noise) before smoothing is backed off.
_CONTAIN_TOL_M = 0.20


@dataclass
class SkeletonChain:
    """One faired medial-axis chain between two skeleton nodes."""
    line: LineString
    # Clearance radius (local pavement half-width) sampled at each vertex of
    # ``line`` — downstream corridor/apron classification reads this.
    radii: list[float] = field(default_factory=list)
    piece: int = 0            # index of the pavement polygon this came from
    end_a_kind: str = "leaf"  # "leaf" | "junction"
    end_b_kind: str = "leaf"


def _polygons(geom) -> list[Polygon]:
    if geom is None or geom.is_empty:
        return []
    if isinstance(geom, Polygon):
        return [geom]
    if isinstance(geom, MultiPolygon):
        return [g for g in geom.geoms if not g.is_empty]
    return [g for g in getattr(geom, "geoms", []) if isinstance(g, Polygon)]


def _sample_rings(poly: Polygon, step: float):
    """Evenly sample every ring of ``poly``.  Returns (points Nx2, ring_id N,
    seq N) where ``seq`` is the sample's index along its own ring — used to
    recognize ridges between ADJACENT samples (boundary noise)."""
    pts, ring_ids, seqs = [], [], []
    rings = [poly.exterior] + list(poly.interiors)
    for ri, ring in enumerate(rings):
        n = max(4, int(math.ceil(ring.length / step)))
        for k in range(n):
            p = ring.interpolate(k * ring.length / n)
            pts.append((p.x, p.y))
            ring_ids.append(ri)
            seqs.append((k, n))
    return np.asarray(pts), np.asarray(ring_ids), seqs


def _adjacent_on_ring(i: int, j: int, ring_ids, seqs) -> bool:
    if ring_ids[i] != ring_ids[j]:
        return False
    ki, ni = seqs[i]
    kj, _ = seqs[j]
    d = abs(ki - kj)
    return min(d, ni - d) <= 1


def _medial_graph(poly: Polygon, step: float, min_r: float) -> nx.Graph:
    """Voronoi medial-axis graph of one polygon.  Nodes are Voronoi vertex
    indices with ``pos`` (x, y) and ``r`` (clearance radius)."""
    pts, ring_ids, seqs = _sample_rings(poly, step)
    if len(pts) < 8:
        return nx.Graph()
    vor = Voronoi(pts)
    verts = vor.vertices

    inside = shapely.contains_xy(poly, verts[:, 0], verts[:, 1])
    # Clearance radius = distance to the nearest boundary sample.  (True
    # clearance is distance to the boundary itself; at 2 m sampling the
    # difference is < 0.25 m, irrelevant for pruning/classification.)
    radii = cKDTree(pts).query(verts)[0]

    g = nx.Graph()
    for (p1, p2), (v1, v2) in zip(vor.ridge_points, vor.ridge_vertices):
        if v1 < 0 or v2 < 0:                      # ridge to infinity
            continue
        if not (inside[v1] and inside[v2]):
            continue
        if radii[v1] < min_r or radii[v2] < min_r:
            continue
        if _adjacent_on_ring(p1, p2, ring_ids, seqs):
            continue                              # perpendicular boundary noise
        d = float(np.hypot(*(verts[v1] - verts[v2])))
        g.add_node(v1, pos=tuple(verts[v1]), r=float(radii[v1]))
        g.add_node(v2, pos=tuple(verts[v2]), r=float(radii[v2]))
        g.add_edge(v1, v2, w=d)
    return g


def _prune_whiskers(g: nx.Graph, factor: float) -> None:
    """Iteratively delete leaf branches shorter than ``factor`` x the clearance
    radius at their attachment node (boundary-bump whiskers).  Mutates ``g``."""
    while True:
        removed = False
        leaves = [n for n in g.nodes if g.degree(n) == 1]
        for leaf in leaves:
            if leaf not in g:
                continue
            # Walk the leaf's degree-2 run up to its attachment node.
            chain = [leaf]
            cur, prev = leaf, None
            length = 0.0
            while g.degree(cur) <= 2:
                nbrs = [n for n in g.neighbors(cur) if n != prev]
                if not nbrs:
                    break                          # isolated path component
                nxt = nbrs[0]
                length += g.edges[cur, nxt]["w"]
                prev, cur = cur, nxt
                chain.append(cur)
            if g.degree(cur) >= 3 and length < factor * g.nodes[cur]["r"]:
                g.remove_nodes_from(chain[:-1])    # keep the attachment node
                removed = True
        if not removed:
            return


def _collapse_chains(g: nx.Graph) -> list[list[int]]:
    """Split the graph into maximal degree-2 runs between junction/leaf nodes.
    Cycles with no junction (a pure ring, e.g. around a hole) come back as one
    closed chain."""
    chains: list[list[int]] = []
    ends = [n for n in g.nodes if g.degree(n) != 2]
    seen_edges: set[frozenset] = set()
    for start in ends:
        for nbr in g.neighbors(start):
            e = frozenset((start, nbr))
            if e in seen_edges:
                continue
            chain = [start, nbr]
            seen_edges.add(e)
            prev, cur = start, nbr
            while g.degree(cur) == 2 and cur not in ends:
                nxt = [n for n in g.neighbors(cur) if n != prev][0]
                seen_edges.add(frozenset((cur, nxt)))
                prev, cur = cur, nxt
                chain.append(cur)
            chains.append(chain)
    # Pure cycles (no non-degree-2 node) — walk each unvisited component.
    for comp in nx.connected_components(g):
        sub = [n for n in comp if g.degree(n) == 2]
        if len(sub) != len(comp) or not comp:
            continue
        start = next(iter(comp))
        nbr = next(iter(g.neighbors(start)))
        if frozenset((start, nbr)) in seen_edges:
            continue
        chain, prev, cur = [start, nbr], start, nbr
        while cur != start:
            nxt = [n for n in g.neighbors(cur) if n != prev][0]
            prev, cur = cur, nxt
            chain.append(cur)
        chains.append(chain)
    return chains


def _fair_chain(coords: np.ndarray, radii: np.ndarray, poly: Polygon,
                step: float, sigma: float):
    """Smooth one chain with an endpoint-pinned smoothing spline; back the
    smoothing off (halving) until the result stays inside ``poly``.  Returns
    (coords Mx2, radii M)."""
    # De-duplicate consecutive identical points (splprep rejects them).
    keep = [0]
    for i in range(1, len(coords)):
        if np.hypot(*(coords[i] - coords[keep[-1]])) > 1e-9:
            keep.append(i)
    coords, radii = coords[keep], radii[keep]
    if len(coords) < 4:
        return coords, radii

    length = float(LineString(coords).length)
    n_out = max(2, int(round(length / step)))
    u_out = np.linspace(0.0, 1.0, n_out + 1)
    # Endpoints get enormous weight so junction welds survive smoothing.
    w = np.ones(len(coords))
    w[0] = w[-1] = 1e6

    allow = poly.buffer(_CONTAIN_TOL_M)
    s = sigma * length
    for _ in range(6):
        try:
            tck, _u = splprep(coords.T, w=w, s=s, k=min(3, len(coords) - 1))
        except Exception:
            break
        out = np.asarray(splev(u_out, tck)).T
        out[0], out[-1] = coords[0], coords[-1]
        if allow.contains(LineString(out)):
            r_out = np.interp(u_out, np.linspace(0, 1, len(radii)), radii)
            return out, r_out
        s *= 0.5
    # Fallback: raw chain, resampled.
    ln = LineString(coords)
    out = np.asarray([ln.interpolate(t * ln.length).coords[0] for t in u_out])
    r_out = np.interp(u_out, np.linspace(0, 1, len(radii)), radii)
    return out, r_out


def _extend_tip(coords: np.ndarray, poly: Polygon, at_start: bool) -> np.ndarray:
    """Extend a leaf tip along its end tangent to the pavement boundary, so a
    dead-end stub's spine reaches its end cap (the medial axis proper stops a
    half-width short).  No-op if the ray exits immediately or the boundary is
    unreachable within 4x the local gap."""
    if len(coords) < 2:
        return coords
    if at_start:
        tip, ref = coords[0], coords[1]
    else:
        tip, ref = coords[-1], coords[-2]
    v = tip - ref
    n = np.hypot(*v)
    if n < 1e-9:
        return coords
    v /= n
    gap = poly.exterior.distance(Point(tip))
    for hole in poly.interiors:
        gap = min(gap, hole.distance(Point(tip)))
    reach = max(4.0, 4.0 * gap)
    ray = LineString([tuple(tip), tuple(tip + v * reach)])
    hit = ray.intersection(poly.boundary)
    if hit.is_empty:
        return coords
    # Nearest boundary hit along the ray, backed off a hair so the tip stays
    # strictly inside the pavement.
    pts = getattr(hit, "geoms", [hit])
    cand = min((p for p in pts if p.geom_type == "Point"),
               key=lambda p: np.hypot(p.x - tip[0], p.y - tip[1]),
               default=None)
    if cand is None:
        return coords
    end = np.asarray([cand.x, cand.y])
    end = end - v * 0.10
    if np.hypot(*(end - tip)) < 0.5:
        return coords
    seg = [end] if at_start else [end]
    return (np.vstack([seg, coords]) if at_start
            else np.vstack([coords, seg]))


def build_pavement_skeleton(
    pav, runway_union=None, *,
    boundary_step: float = _BOUNDARY_STEP_M,
    min_half_width: float = _MIN_HALF_WIDTH_M,
    prune_factor: float = _PRUNE_FACTOR,
    chain_step: float = _CHAIN_STEP_M,
    smooth_sigma: float = _SMOOTH_SIGMA,
    extend_tips: bool = True,
) -> list[SkeletonChain]:
    """Infer a smooth, unbroken taxi spine from the pavement footprint alone.

    ``pav`` is the airport pavement union (``layout.source_pavement_union``);
    ``runway_union`` is subtracted first (runways carry their own solved
    profile — the taxi spine stops at the runway edge).  Returns faired
    :class:`SkeletonChain` s; chains that meet share exact junction endpoints.
    """
    pav_eff = pav
    if runway_union is not None and not runway_union.is_empty:
        try:
            pav_eff = pav.difference(runway_union)
        except Exception:
            pav_eff = pav

    out: list[SkeletonChain] = []
    for pi, poly in enumerate(_polygons(pav_eff)):
        if poly.area < _MIN_PIECE_AREA_M2:
            continue
        g = _medial_graph(poly, boundary_step, min_half_width)
        if g.number_of_edges() == 0:
            continue
        # Drop dust components (a few metres of skeleton in a paint blob).
        for comp in list(nx.connected_components(g)):
            sub_len = sum(g.edges[e]["w"] for e in g.subgraph(comp).edges)
            if sub_len < 8.0:
                g.remove_nodes_from(comp)
        _prune_whiskers(g, prune_factor)
        _prune_whiskers(g, prune_factor)  # second pass after topology change

        for chain in _collapse_chains(g):
            coords = np.asarray([g.nodes[n]["pos"] for n in chain])
            radii = np.asarray([g.nodes[n]["r"] for n in chain])
            if len(coords) < 2:
                continue
            kinds = ["junction" if (n in g and g.degree(n) >= 3) else "leaf"
                     for n in (chain[0], chain[-1])]
            coords, radii = _fair_chain(coords, radii, poly,
                                        chain_step, smooth_sigma)
            if extend_tips:
                if kinds[0] == "leaf":
                    coords2 = _extend_tip(coords, poly, at_start=True)
                    if len(coords2) > len(coords):
                        radii = np.concatenate([[radii[0]], radii])
                    coords = coords2
                if kinds[1] == "leaf":
                    coords2 = _extend_tip(coords, poly, at_start=False)
                    if len(coords2) > len(coords):
                        radii = np.concatenate([radii, [radii[-1]]])
                    coords = coords2
            if len(coords) < 2:
                continue
            ln = LineString(coords)
            if ln.length < 1.0:
                continue
            out.append(SkeletonChain(line=ln, radii=[float(r) for r in radii],
                                     piece=pi, end_a_kind=kinds[0],
                                     end_b_kind=kinds[1]))
    return out
