import Testing
import Foundation
@testable import SceneryKit

@Suite struct GlobalAirportIndexTests {

    /// A fixture exercising every coordinate-derivation path plus a
    /// malformed row and a multi-word name.
    static let fixture = """
    I
    1100 Generated by test

    1 433 0 0 KAAA Alpha International Airport
    1302 icao_code KAAA
    1302 datum_lat 40.5
    1302 datum_lon -80.25
    100 30.00 1 0 0.00 1 2 0 04 99.999 88.888 66 0 2 12 0 0 22 40.1 -80.9 61
    99

    1 200 0 0 KBBB Bravo Field
    100 30.00 1 0 0.00 1 2 0 04 41.5 -81.75 66 0 2 12 0 0 22 41.6 -81.8 61
    99

    17 0 0 0 HELI [H] Downtown Heliport Pad
    1302 gui_label 3D
    102 H1 30.25 -97.75 0.0 12.00 12.00 15 0 0 0.00 0
    99

    16 12 0 0 SPB1 [S] Lakeside Seaplane Base
    101 29.87 0 02 55.5 -130.5 20 55.6 -130.6
    99

    1 500 0 0 KCCC Charlie Regional
    100 30.00 1 0 0.00 1 2 0 04 not-a-number also-bad 66 0 2 12 0 0 22 x y 61
    102 H1 33.75 -84.25 0.0 12.00 12.00 15 0 0 0.00 0
    99

    1 100 0 0 NOCO Airport Without Any Coordinates
    1302 gui_label 2D
    99
    """

    func writeFixture(_ text: String = fixture) throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("gai-\(UUID().uuidString).dat")
        try Data(text.utf8).write(to: url)
        return url
    }

    // MARK: - Parsing

    @Test func parsesEveryAirportTypeAndCoordinateSource() throws {
        let url = try writeFixture()
        defer { try? FileManager.default.removeItem(at: url) }
        let airports = GlobalAirportIndex.parse(aptDatURL: url)

        let byID = Dictionary(uniqueKeysWithValues: airports.map { ($0.id, $0) })

        // Land airport with 1302 datum rows — datum wins over the runway.
        let kaaa = try #require(byID["KAAA"])
        #expect(kaaa.name == "Alpha International Airport")
        #expect(kaaa.latitude == 40.5)
        #expect(kaaa.longitude == -80.25)

        // Land airport WITHOUT datum — falls back to runway row 100 end-1.
        let kbbb = try #require(byID["KBBB"])
        #expect(kbbb.name == "Bravo Field")
        #expect(kbbb.latitude == 41.5)
        #expect(kbbb.longitude == -81.75)

        // Heliport (code 17 + 102 row), multi-word name preserved.
        let heli = try #require(byID["HELI"])
        #expect(heli.name == "[H] Downtown Heliport Pad")
        #expect(heli.latitude == 30.25)
        #expect(heli.longitude == -97.75)

        // Seaplane base (code 16 + 101 row).
        let spb = try #require(byID["SPB1"])
        #expect(spb.name == "[S] Lakeside Seaplane Base")
        #expect(spb.latitude == 55.5)
        #expect(spb.longitude == -130.5)

        // Malformed runway row (non-numeric coords) is skipped; the block's
        // valid 102 helipad still supplies coordinates.
        let kccc = try #require(byID["KCCC"])
        #expect(kccc.latitude == 33.75)
        #expect(kccc.longitude == -84.25)

        // Airport with no derivable coordinates is skipped entirely.
        #expect(byID["NOCO"] == nil)

        // The five coordinate-bearing airports, and nothing spurious.
        #expect(Set(airports.map(\.id)) == ["KAAA", "KBBB", "HELI", "SPB1", "KCCC"])
    }

    @Test func unreadableFileReturnsEmpty() {
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent("does-not-exist-\(UUID().uuidString).dat")
        #expect(GlobalAirportIndex.parse(aptDatURL: missing).isEmpty)
    }

    @Test func lossyDecodingSurvivesLatin1Bytes() throws {
        // A name byte 0xF8 (ø in Latin-1) is invalid UTF-8; parse must not die.
        var bytes = Data("1 13 0 0 ENRM R".utf8)
        bytes.append(0xF8)   // stray Latin-1 byte
        bytes.append(Data("rvik\n1302 datum_lat 64.8\n1302 datum_lon 11.1\n99\n".utf8))
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("gai-latin1-\(UUID().uuidString).dat")
        defer { try? FileManager.default.removeItem(at: url) }
        try bytes.write(to: url)
        let airports = GlobalAirportIndex.parse(aptDatURL: url)
        let a = try #require(airports.first)
        #expect(a.id == "ENRM")
        #expect(a.latitude == 64.8)
        #expect(a.name.hasPrefix("R"))   // U+FFFD substituted, no crash
    }

    // MARK: - Search

    // ABC is an exact id; ABCD/ABCE take ABC as a prefix; XYZ only matches
    // "abc" inside its name; DELTA is the lone name hit for "delta".
    var searchSet: [GlobalAirport] {
        [
            GlobalAirport(id: "ABCE", name: "Echo Field", latitude: 0, longitude: 0),
            GlobalAirport(id: "ABC", name: "Alpha Base", latitude: 0, longitude: 0),
            GlobalAirport(id: "ABCD", name: "Delta Base", latitude: 0, longitude: 0),
            GlobalAirport(id: "XYZ", name: "Contains ABC inside name", latitude: 0, longitude: 0),
            GlobalAirport(id: "ZZZ", name: "Nothing", latitude: 0, longitude: 0),
        ]
    }

    @Test func searchRanksExactThenPrefixThenName() {
        // Exact (ABC) first, then id-prefix (ABCD, ABCE alphabetical), then
        // name-substring (XYZ). ZZZ matches nothing.
        let r = GlobalAirportIndex.search("abc", in: searchSet, limit: 10)
        #expect(r.map(\.id) == ["ABC", "ABCD", "ABCE", "XYZ"])

        // Pure name hit: "delta" appears in ABCD's name only.
        let n = GlobalAirportIndex.search("delta", in: searchSet, limit: 10)
        #expect(n.map(\.id) == ["ABCD"])
    }

    @Test func searchIsCaseInsensitive() {
        let lower = GlobalAirportIndex.search("abc", in: searchSet, limit: 10)
        let upper = GlobalAirportIndex.search("ABC", in: searchSet, limit: 10)
        #expect(lower.map(\.id) == ["ABC", "ABCD", "ABCE", "XYZ"])
        #expect(lower.map(\.id) == upper.map(\.id))
        // Name match ignores case too.
        #expect(GlobalAirportIndex.search("ECHO", in: searchSet, limit: 10).map(\.id) == ["ABCE"])
    }

    @Test func searchRespectsLimitAndEmptyQuery() {
        // Limit truncates after ranking (exact + first prefix kept).
        #expect(GlobalAirportIndex.search("abc", in: searchSet, limit: 2).map(\.id) == ["ABC", "ABCD"])
        #expect(GlobalAirportIndex.search("", in: searchSet, limit: 10).isEmpty)
        #expect(GlobalAirportIndex.search("   ", in: searchSet, limit: 10).isEmpty)
        #expect(GlobalAirportIndex.search("abc", in: searchSet, limit: 0).isEmpty)
    }

    // MARK: - Cache

    @Test func cacheRoundTripReuseAndRebuild() throws {
        let url = try writeFixture()
        defer { try? FileManager.default.removeItem(at: url) }
        let cacheDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("gai-cache-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: cacheDir) }

        // First load builds + writes the cache.
        let first = GlobalAirportIndex.load(aptDatURL: url, cacheDirectory: cacheDir)
        #expect(first.contains { $0.id == "KAAA" })

        // Locate the single cache file and POISON it with a marker airport.
        let cacheFile = try #require(try FileManager.default
            .contentsOfDirectory(at: cacheDir, includingPropertiesForKeys: nil)
            .first { $0.lastPathComponent.hasPrefix("global-airports-") })
        let poisoned = try #require(String(data: try Data(contentsOf: cacheFile), encoding: .utf8))
            .replacingOccurrences(of: "\"KAAA\"", with: "\"POISON\"")
        try Data(poisoned.utf8).write(to: cacheFile)

        // Second load hits the cache — the mutation surfaces (proves no reparse).
        let second = GlobalAirportIndex.load(aptDatURL: url, cacheDirectory: cacheDir)
        #expect(second.contains { $0.id == "POISON" })
        #expect(!second.contains { $0.id == "KAAA" })

        // Touch the mtime → signature moves → the poisoned cache is bypassed
        // and a fresh parse restores the real airport.
        let future = Date().addingTimeInterval(120)
        try FileManager.default.setAttributes([.modificationDate: future], ofItemAtPath: url.path)
        let third = GlobalAirportIndex.load(aptDatURL: url, cacheDirectory: cacheDir)
        #expect(third.contains { $0.id == "KAAA" })
        #expect(!third.contains { $0.id == "POISON" })
    }
}
