name: Feature request
description: Something XPTerrainBuilder should do
labels: ["feature"]
body:
  - type: textarea
    id: want
    attributes:
      label: What should it do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why - what are you trying to build or fly?
  - type: input
    id: example
    attributes:
      label: An airport or tile where this matters
