"""``apt_dat`` block index twins — ONE pass per file, never three scans
per airport (issue #45).

THE DEFECT (owner report, app 1.0.352, tile +40-077): with "Airports on
a tile edge" set to *Ask me every time* no dialog appeared and the
console said the patches were "SKIPPED by your boundary choice".  The
boundary preflight the dialog waits on costs ``find_apt_dat`` per
airport — ``file_has_airport`` + ``_has_pavement``, then ``airside_claim``
through ``read_airport_block``: THREE sequential line-by-line scans of
X-Plane 12's ~500 MB Global Airports apt.dat.  Measured on the owner's
install, warm page cache: 20.1 s for +40-077's seven airports, batched
over five tiles past the app's 60 s preflight bound.

The index must be INVISIBLE: every reader answer, byte for byte, is the
linear scan's — including ``block_sha256``, which stamps patch freshness
and would rebuild every airport in the world if it moved.
"""
from __future__ import annotations

import os

import pytest

from auto_patch_v2.airport import apt_dat as A


def _write(path, lines, newline="\n"):
    with open(path, "wb") as fh:
        fh.write(newline.join(lines).encode("utf-8") + newline.encode())
    return str(path)


HEADER_I = "I"
HEADER_V = "1100 Generated by test"

ROWS = [
    HEADER_I,
    HEADER_V,
    "1 1044 0 0 CYXY Whitehorse",
    "100 45.11 1 0 0.25 0 2 1 31 60.7095 -135.0672 0 0 3 0 0 1 13 "
    "60.7248 -135.0489 0 0 3 0 0 1",
    "110 1 0.25 0 pavement",
    "111 60.7095 -135.0672",
    "1302 city Whitehorse",
    "16 60.0 -135.0 0 CYZZ Seaplane base",
    "100 30.0 1 0 0.25 0 2 1 09 60.1 -135.1 0 0 3 0 0 1 27 "
    "60.2 -135.2 0 0 3 0 0 1",
    "17 0 0 0 CYQQ Heliport only",
    "102 H1 60.3 -135.3 0 20 20 2 0 0 0 0",
    "1 99 0 0 KHZL Hazleton",
    "110 1 0.25 0 apron",
    "99",
]


@pytest.fixture
def apt(tmp_path):
    return _write(tmp_path / "apt.dat", ROWS)


@pytest.fixture
def clean_index():
    """The index is a process-wide cache — never let one test's file
    identity answer another's."""
    A._BLOCK_INDEX.clear()
    yield
    A._BLOCK_INDEX.clear()


# ---------------------------------------------------------------------
# 1. The index and the scan agree, everywhere, byte for byte
# ---------------------------------------------------------------------
@pytest.mark.parametrize("newline", ["\n", "\r\n"])
@pytest.mark.parametrize("icao", ["CYXY", "CYZZ", "CYQQ", "KHZL",
                                  "LFPG", "cyxy"])
def test_the_index_answers_exactly_what_the_scan_answered(
        tmp_path, clean_index, newline, icao):
    path = _write(tmp_path / "apt.dat", ROWS, newline=newline)

    indexed = A.read_airport_block(path, icao)
    scanned = A._scan_airport_block(path, icao.upper())

    assert indexed == scanned
    assert A.file_has_airport(path, icao) is bool(scanned)


def test_the_block_signature_does_not_move(apt, clean_index):
    """``block_sha256`` stamps patch freshness: if the index changed one
    byte of the block text, every airport would rebuild."""
    for icao in ("CYXY", "CYZZ", "CYQQ", "KHZL"):
        assert (A.block_sha256(A.read_airport_block(apt, icao))
                == A.block_sha256(A._scan_airport_block(apt, icao)))


def test_a_repeated_icao_keeps_the_first_block(tmp_path, clean_index):
    """The scan breaks out at the next boundary and never sees the
    second block; the index must not either."""
    rows = ["1 1 0 0 KAAA First", "110 1 0.25 0 a",
            "1 2 0 0 KBBB Other", "110 1 0.25 0 b",
            "1 3 0 0 KAAA Second", "110 1 0.25 0 c", "99"]
    path = _write(tmp_path / "apt.dat", rows)

    block = A.read_airport_block(path, "KAAA")

    assert block == A._scan_airport_block(path, "KAAA")
    assert block[0] == "1 1 0 0 KAAA First"


def test_a_block_running_to_eof_without_the_99_terminator(
        tmp_path, clean_index):
    rows = ["1 1 0 0 KAAA Only", "110 1 0.25 0 a", "111 1.0 2.0"]
    path = _write(tmp_path / "apt.dat", rows)

    assert (A.read_airport_block(path, "KAAA")
            == A._scan_airport_block(path, "KAAA"))


def test_rows_before_the_first_header_belong_to_no_block(apt, clean_index):
    for block in (A.read_airport_block(apt, "CYXY"),
                  A.read_airport_block(apt, "KHZL")):
        assert HEADER_I not in block and HEADER_V not in block


# ---------------------------------------------------------------------
# 2. ONE pass, and it is not re-read per airport
# ---------------------------------------------------------------------
def test_the_file_is_scanned_once_for_all_its_airports(apt, clean_index,
                                                       monkeypatch):
    """THE FIX: ``find_apt_dat``'s three scans per airport become one
    pass per file per process."""
    passes = []
    real = A._build_block_index
    monkeypatch.setattr(A, "_build_block_index",
                        lambda path: passes.append(path) or real(path))

    for icao in ("CYXY", "CYZZ", "CYQQ", "KHZL"):
        assert A.file_has_airport(apt, icao)
        assert A.read_airport_block(apt, icao)
        assert A._has_pavement(apt, icao) in (True, False)

    assert passes == [apt]


# ---------------------------------------------------------------------
# 3. A file that MOVED is re-indexed, never served from stale offsets
# ---------------------------------------------------------------------
def test_a_rewritten_apt_dat_is_reindexed(tmp_path, clean_index):
    """A pack update or a re-download under a running engine."""
    path = str(tmp_path / "apt.dat")
    _write(tmp_path / "apt.dat", ["1 1 0 0 KAAA First", "110 1 0.25 0 a",
                                  "99"])
    assert A.read_airport_block(path, "KAAA")[0] == "1 1 0 0 KAAA First"
    assert A.file_has_airport(path, "KBBB") is False

    # Same path, different bytes — and a different (mtime_ns, size).
    _write(tmp_path / "apt.dat", ["1 7 0 0 KBBB Replaced",
                                  "110 1 0.25 0 b", "99"])

    assert A.read_airport_block(path, "KAAA") is None
    assert A.file_has_airport(path, "KBBB") is True
    assert (A.read_airport_block(path, "KBBB")
            == A._scan_airport_block(path, "KBBB"))


def test_a_file_that_cannot_be_read_is_simply_absent(tmp_path, clean_index):
    missing = str(tmp_path / "nope.dat")

    assert A.file_has_airport(missing, "KAAA") is False
    assert A.read_airport_block(missing, "KAAA") is None


# ---------------------------------------------------------------------
# 4. The safety valve: a wrong index can never return a wrong block
# ---------------------------------------------------------------------
def test_an_index_that_points_at_the_wrong_bytes_falls_back_to_the_scan(
        apt, clean_index, monkeypatch):
    """Whatever the binary pass and the text reader could ever disagree
    about (a lone-CR file, a torn read), the answer stays the scan's."""
    monkeypatch.setattr(A, "_build_block_index",
                        lambda path: {"CYXY": (0, 12), "KHZL": (0, 12)})

    for icao in ("CYXY", "KHZL"):
        assert (A.read_airport_block(apt, icao)
                == A._scan_airport_block(apt, icao))
