"""A degenerate sliver never kills a tile (round 15, R15-1).

Triangle's ``.ele`` format declares the triangle ATTRIBUTE column REAL,
and Triangle4XP writes a genuine float in it when it had to mesh inside
a degenerate sliver.  Tile +25+051 (OTHH) came back on 2026-08-11 with
two triangles carrying the attribute ``1.4375`` — their four corners one
point down to the 11th decimal — and
``O4_Mesh_Utils.post_process_nodes_altitudes`` died on ``int('1.4375')``,
taking the whole tile with it.

The law: vertex index columns stay strict ints, the attribute is read as
a real, an integral real is its int, and a NON-integral one is a measured
degeneracy — the triangle is treated as the dummy attribute (no altitude
post-treatment, which for a sub-micron sliver is exact) and counted into
one loud line.

Everything is hermetic under ``tmp_path``: the tile is a
``types.SimpleNamespace`` and the ``.node`` / ``.ele`` pair is hand-written
(same harness pattern as ``tests/test_mesh_write_atomic.py``).
"""

from __future__ import annotations

import types

import pytest

import O4_File_Names as FNAMES
import O4_Mesh_Utils
import O4_UI_Utils as UI
import O4_Vector_Utils as VECT

ATTR = VECT.Vector_Map.dico_attributes

TILE_LATITUDE = 25
TILE_LONGITUDE = 51

# Four vertices, six columns each: longitude offset, latitude offset,
# elevation, normal x, normal y, interpolated (vector) elevation.  The
# elevation and the interpolated elevation differ so that an INTERP_ALT
# post-treatment is visible in the output.
RAW_ELEVATION = 100.0
INTERPOLATED_ELEVATION = 7.0


def _make_tile(build_directory) -> types.SimpleNamespace:
    return types.SimpleNamespace(
        build_dir=str(build_directory),
        lat=TILE_LATITUDE,
        lon=TILE_LONGITUDE,
        iterate=0,
        water_smoothing=0,
        sea_smoothing_mode="zero",
    )


def _seed_node_file(tile, nbr_pt: int = 4) -> None:
    corners = [(0.0, 0.0), (0.001, 0.0), (0.001, 0.001), (0.0, 0.001)]
    with open(FNAMES.output_node_file(tile), "w") as handle:
        handle.write("%d 2 4 0\n" % nbr_pt)
        for index in range(nbr_pt):
            (longitude_offset, latitude_offset) = corners[index % 4]
            handle.write(
                "%d %.15f %.15f %.15f 0 0 %.15f\n"
                % (
                    index + 1,
                    longitude_offset,
                    latitude_offset,
                    RAW_ELEVATION,
                    INTERPOLATED_ELEVATION,
                )
            )
        handle.write("# Generated by a test\n")


def _seed_ele_file(tile, attributes) -> None:
    """One triangle per attribute *text*, all on the same four vertices."""
    with open(FNAMES.output_ele_file(tile), "w") as handle:
        handle.write("%d 3 1\n" % len(attributes))
        for index, attribute_text in enumerate(attributes):
            handle.write(
                "%d 1 2 3 %s\n" % (index + 1, attribute_text)
            )
        handle.write("# Generated by a test\n")


def _run_post_process(tile, monkeypatch):
    """Run the post-treatment, returning (vertices, loud lines)."""
    loud_lines = []

    def recording_lvprint(min_verbosity, *args):
        loud_lines.append(" ".join(str(argument) for argument in args))

    monkeypatch.setattr(UI, "lvprint", recording_lvprint)
    return (O4_Mesh_Utils.post_process_nodes_altitudes(tile), loud_lines)


################################################################################
# The column reader itself


@pytest.mark.parametrize(
    "text, expected",
    [
        ("0", ATTR["DUMMY"]),
        ("16", 16),
        ("16.0", 16),
        ("16.0000001", 16),
        ("10", 10),
    ],
)
def test_integral_attributes_read_as_their_int(text, expected):
    assert O4_Mesh_Utils.read_triangle_attribute(text) == (expected, True)


@pytest.mark.parametrize("text", ["1.4375", "0.5", "-2.25", "nan", "inf"])
def test_non_integral_attributes_are_the_dummy_attribute(text):
    assert O4_Mesh_Utils.read_triangle_attribute(text) == (
        ATTR["DUMMY"],
        False,
    )


################################################################################
# post_process_nodes_altitudes


def test_float_attribute_is_contained_and_reported(tmp_path, monkeypatch):
    """The float attribute that killed +25+051: no crash, no
    post-treatment for that triangle, one loud line naming the count, the
    triangle index, the attribute text and a vertex coordinate."""
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    _seed_ele_file(tile, ["1.4375", "1.4375", "0"])

    (vertices, loud_lines) = _run_post_process(tile, monkeypatch)

    # Untreated: the elevation column keeps the raw mesh elevation
    # instead of being overwritten by the vector one.
    assert vertices[2] == RAW_ELEVATION
    assert len(loud_lines) == 1
    reported = loud_lines[0]
    assert "2" in reported.split()
    assert "1.4375" in reported
    assert "#1" in reported
    assert "%.9f" % TILE_LONGITUDE in reported


def test_integral_float_attribute_keeps_its_meaning(tmp_path, monkeypatch):
    """"16.0" is the RUNWAY attribute, not a degeneracy: it is treated
    (>= INTERP_ALT) and no loud line is emitted."""
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    _seed_ele_file(tile, ["16.0"])

    (vertices, loud_lines) = _run_post_process(tile, monkeypatch)

    assert vertices[2] == INTERPOLATED_ELEVATION
    assert loud_lines == []


def test_integer_attribute_is_unchanged(tmp_path, monkeypatch):
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    _seed_ele_file(tile, ["16"])

    (vertices, loud_lines) = _run_post_process(tile, monkeypatch)

    assert vertices[2] == INTERPOLATED_ELEVATION
    assert loud_lines == []


def test_attribute_ending_in_zero_is_not_skipped(tmp_path, monkeypatch):
    """The old fast-skip tested the last CHARACTER: "10"
    (INTERP_ALT|SEA) went untreated because it ends in a zero."""
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    _seed_ele_file(tile, ["10"])

    (vertices, loud_lines) = _run_post_process(tile, monkeypatch)

    assert vertices[2] == INTERPOLATED_ELEVATION
    assert loud_lines == []


def test_dummy_attribute_is_still_skipped(tmp_path, monkeypatch):
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    _seed_ele_file(tile, ["0"])

    (vertices, loud_lines) = _run_post_process(tile, monkeypatch)

    assert vertices[2] == RAW_ELEVATION
    assert loud_lines == []


def test_vertex_columns_stay_strict_integers(tmp_path, monkeypatch):
    """Only the attribute column is real: a fractional vertex index is a
    corrupt file and must not be silently rounded into a valid index."""
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    with open(FNAMES.output_ele_file(tile), "w") as handle:
        handle.write("1 3 1\n")
        handle.write("1 1.5 2 3 8\n")

    monkeypatch.setattr(UI, "lvprint", lambda *args: None)
    with pytest.raises(ValueError):
        O4_Mesh_Utils.post_process_nodes_altitudes(tile)


################################################################################
# write_mesh_file — the .mesh attribute column stays integral


def test_mesh_file_attribute_column_is_normalised(tmp_path, monkeypatch):
    """Every reader of the written mesh (``read_mesh_file``, the mask
    builders, auto_patch's mesh sampler) parses the attribute as an int,
    so the float never reaches them."""
    tile = _make_tile(tmp_path)
    _seed_node_file(tile)
    _seed_ele_file(tile, ["1.4375", "16.0", "8"])
    monkeypatch.setattr(UI, "lvprint", lambda *args: None)
    vertices = O4_Mesh_Utils.post_process_nodes_altitudes(tile)

    O4_Mesh_Utils.write_mesh_file(tile, vertices)

    mesh_path = FNAMES.mesh_file(tile.build_dir, tile.lat, tile.lon)
    with open(mesh_path, "r") as handle:
        lines = handle.read().splitlines()
    triangle_header_index = lines.index("Triangles")
    triangle_rows = lines[
        triangle_header_index + 2 : triangle_header_index + 5
    ]
    assert triangle_rows == ["1 2 3 0", "1 2 3 16", "1 2 3 8"]

    (_, _, _, nbr_tris, _, tri_types) = O4_Mesh_Utils.read_mesh_file(
        mesh_path
    )
    assert nbr_tris == 3
    assert list(tri_types) == [ATTR["DUMMY"], 16, ATTR["INTERP_ALT"]]
