"""``tools/fetch_airport_elevation_insets.py --witness`` (promoted from the
holder lanes' scratch ``witness.py``, RULINGS 7e90032): the apt.dat airport
(footprint + runway ends) and the witness record read from a cached inset +
sidecar -- ARP sanity through the harness's own check, airport cover over
the footprint box, per-rung rows.  Synthetic raster, no network."""

import importlib.util
import json
import os
import sys
from pathlib import Path

import numpy
import pytest

ROOT = Path(__file__).resolve().parents[1]

try:
    from osgeo import gdal, osr

    HAS_GDAL = True
except Exception:                                        # pragma: no cover
    HAS_GDAL = False


def _tool():
    spec = importlib.util.spec_from_file_location(
        "fetch_inset_witness_twin",
        ROOT / "tools" / "fetch_airport_elevation_insets.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["fetch_inset_witness_twin"] = mod
    spec.loader.exec_module(mod)
    return mod


# One runway 05/23 from (35.000, -79.000) to (35.010, -78.990), field
# elevation 328 ft = 99.97 m.
APT = """I
1200 Generated by test
1    328 0 0 KTST Test Field
100 45.00 1 0 0.25 1 2 1 05 35.00000000 -79.00000000 0 0 2 0 0 0 23 35.01000000 -78.99000000 0 0 2 0 0 0
110 1 0.25 0 apron
111 35.00000000 -79.00000000
111 35.01000000 -79.00000000
113 35.01000000 -78.99000000
1302 datum_lat 35.00500000
1302 datum_lon -78.99500000
1    100 0 0 KOTH Other
100 45.00 1 0 0.25 1 2 1 09 40.0 -100.0 0 0 2 0 0 0 27 40.0 -99.99 0 0 2 0 0 0
99
"""


def _raster(path, box, value):
    size = 200
    dataset = gdal.GetDriverByName("GTiff").Create(
        path, size, size, 1, gdal.GDT_Float32)
    (west, south, east, north) = box
    dataset.SetGeoTransform((west, (east - west) / size, 0.0, north, 0.0,
                             -(north - south) / size))
    srs = osr.SpatialReference()
    srs.ImportFromEPSG(4326)
    dataset.SetProjection(srs.ExportToWkt())
    values = numpy.full((size, size), value, dtype=numpy.float32)
    values[:, : size // 4] = -32768.0          # west quarter is nodata
    band = dataset.GetRasterBand(1)
    band.SetNoDataValue(-32768.0)
    band.WriteArray(values)
    dataset = None


@pytest.mark.skipif(not HAS_GDAL, reason="no osgeo")
def test_witness_record_from_apt_dat_and_sidecar(tmp_path):
    mod = _tool()
    apt = tmp_path / "apt.dat"
    apt.write_text(APT, encoding="utf-8", newline="\n")
    (polygon, ends) = mod.apt_dat_airport(str(apt), "ktst",
                                          str(tmp_path / "scratch"))
    assert [name for (name, _la, _lo) in ends] == ["05", "23"]
    (west, south, east, north) = polygon.bounds
    assert (round(west, 6), round(north, 6)) == (-79.0, 35.01)
    inset = str(tmp_path / "KTST_fake.tif")
    _raster(inset, (-79.02, 34.99, -78.97, 35.02), 100.5)
    with open(str(tmp_path / "KTST_fake.json"), "w", encoding="utf-8",
              newline="\n") as handle:
        json.dump({"provider": "FAKE", "native_resolution_m": 0.95,
                   "resolution_m": 0.95, "vertical_unit_source": "ftUS",
                   "vertical_unit_applied": "m", "bytes_fetched": 12,
                   "ladder": {"delivered_provider": "FAKE",
                              "delivered_rung": 1, "delivered_label": "F",
                              "rungs_tried": [
                                  {"rung": 0, "label": "1 meter",
                                   "provider": "USGS3DEP",
                                   "outcome": "no-coverage",
                                   "valid_fraction": 0.0},
                                  {"rung": 1, "label": "F",
                                   "provider": "FAKE",
                                   "outcome": "delivered",
                                   "valid_fraction": 0.75,
                                   "vertical_unit_applied": "m"}]}},
                  handle)
    record = mod.witness_record(inset, str(apt), "KTST", polygon, ends, 4.2)
    assert record["delivered_provider"] == "FAKE"
    assert record["delivered_rung"] == 1
    assert record["valid_fraction"] == pytest.approx(0.75)
    assert record["airport_valid_fraction"] == 1.0   # footprint east of hole
    assert record["vertical_unit_applied"] == "m"
    assert record["bytes_fetched"] == 12
    arp = record["arp_sanity"]
    assert arp["status"] == "ok"
    assert arp["arp"] == [35.005, -78.995]
    assert arp["insets"][0]["delta_m"] == pytest.approx(100.5 - 99.974, abs=0.01)
    assert [end["inset_m"] for end in record["runway_ends"]] == [100.5, 100.5]
    assert [row["outcome"] for row in record["rungs"]] == [
        "no-coverage", "delivered"]
    assert record["rungs"][1]["vertical_unit_applied"] == "m"


def test_witness_refuses_without_a_lane_local_dir(monkeypatch, capsys):
    mod = _tool()
    monkeypatch.setattr(sys, "argv", [
        "fetch_airport_elevation_insets.py", "--witness", "KTST"])
    assert mod.main() == 2
    assert "--elevation-data-dir" in capsys.readouterr().out


def test_runway_only_block_still_has_a_footprint(tmp_path):
    pytest.importorskip("osgeo")   # the gap census's footprint reads GDAL
    mod = _tool()
    apt = tmp_path / "apt.dat"
    apt.write_text(APT, encoding="utf-8", newline="\n")
    (polygon, ends) = mod.apt_dat_airport(str(apt), "KOTH",
                                          str(tmp_path / "scratch"))
    assert not polygon.is_empty and polygon.area > 0
    assert [name for (name, _la, _lo) in ends] == ["09", "27"]
