"""THE WATER BIT OUTRANKS THE INTERP_ALT SEED (owner RULINGS 2026-09-09m;
mechanism 09o (3); spec ``docs/specs/auto-patch-v2/water-datum-spec.md``
§4).

``post_process_nodes_altitudes`` used to test ``attr >= INTERP_ALT``
first, so a water triangle an INTERP_ALT seed reached was exempt from sea
levelling and copied the DEM instead.  Measured on the owner's OTHH build
(1.0.297, ``Data+25+051.mesh``): 2,180 triangles came out ``SEA|INTERP_ALT``
(attribute 10) over 13.7 km² of water, 1,692 of them carrying a 3.962 m
step one triangle wide — the canal sawtooth the owner read.

The twins use the same hermetic ``.node``/``.ele`` harness as
``tests/test_mesh_degenerate_attribute.py``.
"""
from __future__ import annotations

import types

import pytest

import O4_File_Names as FNAMES
import O4_Mesh_Utils
import O4_UI_Utils as UI
import O4_Vector_Utils as VECT

ATTR = VECT.Vector_Map.dico_attributes

TILE_LATITUDE = 25
TILE_LONGITUDE = 51

#: The mesh's own elevation — the flat-site plateau that flooded the
#: canal — and the vector (column 5) value an INTERP_ALT seed copies.
RAW_ELEVATION = 3.962
INTERPOLATED_ELEVATION = 7.0


def _make_tile(build_directory, *, water_smoothing=0,
               sea_smoothing_mode="zero") -> types.SimpleNamespace:
    return types.SimpleNamespace(
        build_dir=str(build_directory),
        lat=TILE_LATITUDE,
        lon=TILE_LONGITUDE,
        iterate=0,
        water_smoothing=water_smoothing,
        sea_smoothing_mode=sea_smoothing_mode,
    )


def _seed(tile, attributes) -> None:
    corners = [(0.0, 0.0), (0.001, 0.0), (0.001, 0.001), (0.0, 0.001)]
    with open(FNAMES.output_node_file(tile), "w") as handle:
        handle.write("4 2 4 0\n")
        for index, (dlon, dlat) in enumerate(corners):
            handle.write("%d %.15f %.15f %.15f 0 0 %.15f\n"
                         % (index + 1, dlon, dlat, RAW_ELEVATION,
                            INTERPOLATED_ELEVATION))
        handle.write("# Generated by a test\n")
    with open(FNAMES.output_ele_file(tile), "w") as handle:
        handle.write("%d 3 1\n" % len(attributes))
        for index, text in enumerate(attributes):
            handle.write("%d 1 2 3 %s\n" % (index + 1, text))
        handle.write("# Generated by a test\n")


def _run(tile, monkeypatch):
    monkeypatch.setattr(UI, "lvprint", lambda *a, **k: None)
    return O4_Mesh_Utils.post_process_nodes_altitudes(tile)


# ── the ruling ──────────────────────────────────────────────────────────

def test_a_seeded_sea_triangle_levels_to_zero(tmp_path, monkeypatch):
    """attr 10 = SEA|INTERP_ALT — the OTHH canal's own attribute."""
    tile = _make_tile(tmp_path)
    _seed(tile, [str(ATTR["SEA"] | ATTR["INTERP_ALT"])])
    vertices = _run(tile, monkeypatch)
    assert vertices[2] == 0.0, "the water bit must outrank the seed"


def test_a_seeded_inland_water_triangle_takes_water_smoothing(tmp_path,
                                                              monkeypatch):
    """attr 9 = WATER|INTERP_ALT: inland water, so the water branch (a
    per-triangle mean), never the seed's copy of column 5."""
    tile = _make_tile(tmp_path, water_smoothing=1)
    _seed(tile, [str(ATTR["WATER"] | ATTR["INTERP_ALT"])])
    vertices = _run(tile, monkeypatch)
    assert vertices[2] == pytest.approx(RAW_ELEVATION)
    assert vertices[2] != INTERPOLATED_ELEVATION


def test_a_seeded_runway_over_water_is_water_too(tmp_path, monkeypatch):
    """An apt.dat region bit does not shelter water either: the rule is
    the WATER BIT, not the seed's identity."""
    tile = _make_tile(tmp_path)
    _seed(tile, [str(ATTR["SEA"] | ATTR["RUNWAY"])])
    assert _run(tile, monkeypatch)[2] == 0.0


# ── :968-970 is unchanged for non-water ─────────────────────────────────

def test_a_plain_interp_alt_triangle_still_copies_the_vector_value(
        tmp_path, monkeypatch):
    """The patch pavement interior — bit 8 ALONE, which is what
    ``PATCH_RING_MARKER`` guarantees it keeps."""
    tile = _make_tile(tmp_path)
    _seed(tile, [str(ATTR["INTERP_ALT"])])
    assert _run(tile, monkeypatch)[2] == INTERPOLATED_ELEVATION


def test_an_apt_dat_region_triangle_still_copies_the_vector_value(
        tmp_path, monkeypatch):
    tile = _make_tile(tmp_path)
    _seed(tile, [str(ATTR["RUNWAY"])])
    assert _run(tile, monkeypatch)[2] == INTERPOLATED_ELEVATION


def test_bare_sea_is_unchanged(tmp_path, monkeypatch):
    tile = _make_tile(tmp_path)
    _seed(tile, [str(ATTR["SEA"])])
    assert _run(tile, monkeypatch)[2] == 0.0
