"""Offline replay of the main-yield ``feasibility_project`` (fp#8) — the
projection lane's measurement instrument.

WHY IT EXISTS.  Slice B stage B3 needed to re-drive one projection after
each source edit without paying a 1-3 min build; the cycle-6 attribution
lane needed to re-drive the SAME projection at a different sweep budget
and with individual constraint classes removed, to separate convergence
from structure.  Both are one need: **run production's projection, on
production's exact inputs, offline, under a stated intervention.**

WHAT IT REPLAYS.  ``O4_DUMP_SOLVE_STATE`` pickles the fp#8 inputs right
before the call in ``route_profile/solve.py``.  The snapshot is
code-independent input data, so editing ``one_solve.py`` changes only the
REPLAY, never the snapshot — one snapshot serves any number of replays.

FIDELITY — READ THIS BEFORE QUOTING A NUMBER.  A dump written before
2026-08-06 carries only the FLATTENED ``joint_edges`` list, which has
lost each entry's law FAMILY, its ``envelope_skip`` flag and its lazy
state; replaying from it judges a DIFFERENT constraint set from
production's fp#8.  Dumps from 2026-08-06 on carry ``joint_entries`` +
``fp8_kwargs`` and reconstruct the call verbatim.  This tool SAYS which
of the two it got, and refuses to call the degraded one faithful.  A lazy
(flatness-certified) entry's body pairs are generated by a thunk that
cannot be pickled: those entries are counted and named in the header, not
silently dropped.

Usage (run from ``Ortho4XP/``):

    # 1. Capture the snapshot once (one build):
    venv/bin/python tools/interval_reach_replay.py snapshot HECA

    # 2. Replay production's projection verbatim:
    venv/bin/python tools/interval_reach_replay.py replay HECA

    # 3. The SWEEP-BUDGET ladder — is the residual convergence or
    #    structure?  (``--sweeps`` imposes a budget; the exit report then
    #    says the budget was IMPOSED rather than derived.)
    venv/bin/python tools/interval_reach_replay.py replay HECA --sweeps 49600

    # 4. The CONSTRAINT-CLASS ladder — which layer owns the floor?
    venv/bin/python tools/interval_reach_replay.py replay HECA \\
        --arm no-boxes --sweeps 49600
    venv/bin/python tools/interval_reach_replay.py replay HECA \\
        --arm pure-symmetric --sweeps 49600

    # 5. SLAB-CLASS decomposition — drop one law family's edges and see
    #    what it was worth (repeatable; families are the same names the
    #    exit report's family axis prints).
    venv/bin/python tools/interval_reach_replay.py replay HECA \\
        --drop-family graded_strip:adjacent_ground --sweeps 49600

Arms (``--arm``), each a NAMED INTERVENTION on the same input set:

    production      everything as production passed it (default)
    free-hard       every hard anchor freed (immovability dropped)
    free-seams      only the ``seed_rwy_seam`` anchors freed
    no-boxes        bounded-yield boxes dropped + hard freed; intervals kept
    no-intervals    signed interval/slab edges dropped; boxes kept
    pure-symmetric  symmetric law edges only, all nodes free, no boxes
                    — FEASIBLE BY CONSTRUCTION (``z ≡ const`` satisfies
                    every constraint), so any residual it leaves is
                    convergence, by construction, and nothing else.

Every run prints the projection's own exit report — including the family
axis, which this tool always supplies from the dump's ``family_by_pair``.
"""
import argparse
import os
import pickle
import sys
import time

os.environ.setdefault("O4_LOG_VERBOSITY", "1")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _p in (os.path.join(ROOT, "src"), ROOT, os.path.join(ROOT, "tests"),
           os.path.join(ROOT, "tools")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

ARMS = ("production", "free-hard", "free-seams", "no-boxes", "no-intervals",
        "pure-symmetric")


def snapshot_path(icao):
    return f"/tmp/{icao}_interval_reach_state.pkl"


def do_snapshot(icao, path):
    # Gates ON (skirt + gap) so the interval edges are produced, and dump the
    # main-yield projection inputs.  Pinned hash seed for a reproducible build.
    os.environ["O4_ONE_SOLVE_TERRAIN"] = "1"
    os.environ["O4_ONE_SOLVE_TERRAIN_RUNWAY_END_SKIRT"] = "1"
    os.environ["O4_ONE_SOLVE_TERRAIN_GAP_FILL_SPINE"] = "1"
    os.environ["O4_DUMP_SOLVE_STATE"] = path
    os.environ.setdefault("PYTHONHASHSEED", "0")
    # Ground-truth counters from the REAL build (not just the replay).
    os.environ["O4_FP_REENTRY_DEBUG"] = "1"
    os.environ["O4_STEP_DEBUG"] = "1"

    from conftest import xplane_root
    from auto_patch.pipeline import build_airport_pavement

    t0 = time.time()
    build_airport_pavement(icao, xplane_root(), compute_elevations=True)
    print(f"[snapshot] build done in {time.time() - t0:.1f}s; dump at {path}")


def _entries_from(state):
    """``(entries, faithful, note)`` — the joint as ENTRIES, not a flat list.

    ``faithful`` is False for a pre-2026-08-06 dump, whose flat
    ``joint_edges`` cannot carry a family, an ``envelope_skip`` flag or a
    lazy marker.  The caller prints the note; nothing here guesses.
    """
    raw = state.get("joint_entries")
    if raw is None:
        edges = [tuple(e) for e in state["joint_edges"]]
        return ([{"edges": edges}], False,
                "LEGACY dump: flat joint_edges only — no family axis, no "
                "envelope_skip, no lazy accounting. NOT a faithful fp#8.")
    entries = []
    n_lazy = 0
    for e in raw:
        if e.get("lazy"):
            n_lazy += 1
        entries.append({
            "family": e.get("family"), "role": e.get("role"),
            "ref": e.get("ref"),
            "envelope_skip": bool(e.get("envelope_skip")),
            "edges": [tuple(x) for x in e.get("edges") or ()],
        })
    note = f"{len(entries)} joint entry(ies)"
    if n_lazy:
        note += (f"; {n_lazy} were STILL LAZY at dump time — their body "
                 f"pairs are thunk-generated and not in this snapshot")
    return entries, True, note


def _apply_arm(arm, entries, hard, node_bounds, group_bounds, state):
    """Return ``(entries, hard, node_bounds, group_bounds)`` for one arm."""
    if arm == "production":
        return entries, hard, node_bounds, group_bounds
    if arm == "free-seams":
        cat = state.get("hard_cat") or {}
        seams = {int(i) for i, c in cat.items() if c == "seed_rwy_seam"}
        return entries, {i for i in hard if i not in seams}, \
            node_bounds, group_bounds
    if arm == "free-hard":
        return entries, set(), node_bounds, group_bounds
    if arm == "no-boxes":
        return entries, set(), None, None
    if arm == "no-intervals":
        return ([{**e, "edges": [x for x in e["edges"] if len(x) < 4]}
                 for e in entries], hard, node_bounds, group_bounds)
    if arm == "pure-symmetric":
        return ([{**e, "edges": [x for x in e["edges"] if len(x) < 4]}
                 for e in entries], set(), None, None)
    raise SystemExit(f"unknown arm {arm!r} (choose from {', '.join(ARMS)})")


def _drop_families(entries, families):
    """Remove whole entries whose family tag matches — the slab-class knife.

    The tag rule is the projection's own (``one_solve._entry_family_tag``),
    so a name printed by the exit report's family axis is exactly the name
    accepted here.  Catch-all entries (the unified graph) are refused: an
    axis label there is a PER-EDGE resolution, and dropping the whole
    entry would delete unrelated law.
    """
    from auto_patch.elevation_per_surface.route_profile.one_solve import (
        _entry_family_tag, _CATCH_ALL_FAMILY_TAGS)
    bad = [f for f in families if f in _CATCH_ALL_FAMILY_TAGS]
    if bad:
        raise SystemExit(
            f"--drop-family {bad!r} names a CONSTRUCTION-SITE tag, not a "
            f"law: those entries carry many families resolved per edge and "
            f"dropping the entry would delete unrelated law.")
    want = set(families)
    kept, dropped, dropped_edges = [], 0, 0
    for e in entries:
        if _entry_family_tag(e) in want:
            dropped += 1
            dropped_edges += len(e["edges"])
            continue
        kept.append(e)
    print(f"[arm] --drop-family {sorted(want)}: removed {dropped} entry(ies) "
          f"/ {dropped_edges} edge(s)")
    return kept


def _drop_interval_families(entries, families):
    """Strip only the INTERVAL edges of matching entries — the slab knife.

    Safe where :func:`_drop_families` is not: removing an entry's signed
    slabs never removes a symmetric cap, so a catch-all-tagged entry (the
    solve's own joint, which is where the §10 rod slabs live) can be
    knifed without deleting the unified graph's law along with it.
    """
    from auto_patch.elevation_per_surface.route_profile.one_solve import (
        _entry_family_tag)
    want = set(families)
    kept, dropped = [], 0
    for e in entries:
        if _entry_family_tag(e) in want:
            keep = [x for x in e["edges"] if len(x) < 4]
            dropped += len(e["edges"]) - len(keep)
            e = {**e, "edges": keep}
        kept.append(e)
    print(f"[arm] --drop-interval-family {sorted(want)}: removed {dropped} "
          f"slab edge(s)")
    return kept


def do_replay(icao, path, *, arm, sweeps, hard_cap, drop_family,
              drop_interval_family, quiet_families):
    with open(path, "rb") as fh:
        state = pickle.load(fh)
    entries, faithful, note = _entries_from(state)
    kw = dict(state.get("fp8_kwargs") or {})
    elev = list(state["elev"])
    hard = {int(i) for i in state["yield_hard"]}
    pad_groups = [set(g) for g in state.get("pad_groups", [])] or None
    node_bounds = kw.get("node_bounds")
    group_bounds = kw.get("group_bounds")
    family_of = state.get("family_by_pair")
    band = state.get("node_band")
    env_band = band if kw.get("env_band_is_node_band") else None
    gs_witness = kw.get("gs_witness")
    if gs_witness:
        gs_witness = (frozenset(gs_witness[0]), gs_witness[1])
    excluded = kw.get("witness_excluded")
    gs_pin = kw.get("gs_pin_nodes")

    print(f"[replay] {icao} arm={arm} "
          f"block={'DERIVED' if sweeps is None else sweeps} "
          f"hard_cap={'DEFAULT' if hard_cap is None else hard_cap}")
    print(f"[replay] {'FAITHFUL' if faithful else 'DEGRADED'}: {note}")
    if not faithful:
        print("[replay] re-capture with `snapshot` on a 2026-08-06+ tree "
              "before quoting this as fp#8.")
    if drop_family:
        entries = _drop_families(entries, drop_family)
    if drop_interval_family:
        entries = _drop_interval_families(entries, drop_interval_family)
    entries, hard, node_bounds, group_bounds = _apply_arm(
        arm, entries, hard, node_bounds, group_bounds, state)
    n_edges = sum(len(e["edges"]) for e in entries)
    n_int = sum(1 for e in entries for x in e["edges"] if len(x) >= 4)
    print(f"[replay] nodes={len(elev)} raw_edges={n_edges} "
          f"interval={n_int} hard={len(hard)} "
          f"pad_groups={len(pad_groups) if pad_groups else 0} "
          f"node_bounds={len(node_bounds) if node_bounds else 0} "
          f"group_bounds={len(group_bounds) if group_bounds else 0}")

    from auto_patch.elevation_per_surface.route_profile.one_solve import (
        feasibility_project)
    broken: set = set()
    t0 = time.time()
    rem, bh = feasibility_project(
        elev, entries, hard,
        max_iters=sweeps,
        sweep_hard_cap=hard_cap,
        force_scalar=True,
        flat_groups=pad_groups,
        broken_out=broken,
        interval_yield_from=state.get("interval_yield_from"),
        group_bounds=group_bounds,
        node_bounds=node_bounds,
        gs_pin_nodes=(set(gs_pin) if gs_pin else None),
        witness_limited=gs_witness,
        witness_excluded=(set(excluded) if excluded else None),
        env_band=env_band,
        family_of=(None if quiet_families else family_of))
    dt = time.time() - t0
    print(f"[replay] projection {dt:.2f}s  rem={rem} both_hard={bh} "
          f"broken={len(broken)}")
    return rem, bh


def main():
    ap = argparse.ArgumentParser(
        prog="interval_reach_replay.py",
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("mode", choices=("snapshot", "replay"))
    ap.add_argument("icao", nargs="?", default="CYXY")
    ap.add_argument("--state", default=None,
                    help="snapshot path (default /tmp/<ICAO>_interval_"
                         "reach_state.pkl)")
    ap.add_argument("--sweeps", type=int, default=None,
                    help="IMPOSE the sweep BLOCK instead of deriving it — "
                         "the budget ladder (the exit report then says the "
                         "block was imposed)")
    ap.add_argument("--hard-cap", type=int, default=None,
                    help="the absolute sweep ceiling. With --sweeps this "
                         "is how you drive a stated block to a stated "
                         "budget and read the whole block trajectory; "
                         "alone it overrides config.SWEEP_BUDGET_MAX")
    ap.add_argument("--arm", default="production", choices=ARMS,
                    help="named constraint-class intervention")
    ap.add_argument("--drop-family", action="append", default=[],
                    metavar="FAMILY",
                    help="drop every joint entry with this family tag "
                         "(repeatable) — the slab-class knife")
    ap.add_argument("--drop-interval-family", action="append", default=[],
                    metavar="FAMILY",
                    help="drop only the INTERVAL/slab edges of entries with "
                         "this family tag (repeatable) — the slab knife; "
                         "safe on catch-all tags, where --drop-family is not")
    ap.add_argument("--no-families", action="store_true",
                    help="suppress the exit report's family axis")
    args = ap.parse_args()
    path = args.state or snapshot_path(args.icao)
    if args.mode == "snapshot":
        do_snapshot(args.icao, path)
        return
    os.environ["O4_FP_REENTRY_DEBUG"] = "1"
    os.environ["O4_STEP_DEBUG"] = "1"
    do_replay(args.icao, path, arm=args.arm, sweeps=args.sweeps,
              hard_cap=args.hard_cap, drop_family=args.drop_family,
              drop_interval_family=args.drop_interval_family,
              quiet_families=args.no_families)


if __name__ == "__main__":
    main()
