#!/usr/bin/env python3
"""Windows VERSION RESOURCE for the frozen Qt app (RELEASES-PLAN §C1).

Windows reads an exe's identity out of its embedded version resource: it is
what Explorer's Properties -> Details pane shows, what SmartScreen quotes,
and what a beta tester can read off a binary they downloaded three weeks
ago.  Without one, ``XPTerrainBuilder.exe`` shows blank fields and no
version at all.

PyInstaller takes it as a text file of a ``VSVersionInfo(...)`` expression
(``EXE(version=...)``), so this emits exactly that, from the same two
tracked files ``scripts/write_version_txt.sh`` reads — one source of truth
for the version triple:

    app     Sources/XPTerrainBuilder/Resources/VERSION   -> FileVersion,
                                                            ProductVersion
    engine  Ortho4XP/src/O4_Version.py                   -> Comments
    sha     $GITHUB_SHA (else git)                       -> Comments

Usage: python3 scripts/make_version_resource.py <out-file> [--exe-name NAME]

The four-part Windows version tuple is the app triple plus a trailing 0
(``1.0.347`` -> ``1, 0, 347, 0``).  A tree with no version files at all
(a source tarball) gets 0.0.0.0 and says so, rather than inventing a
number.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
APP_VERSION_FILE = REPO_ROOT / "Sources" / "XPTerrainBuilder" / "Resources" / "VERSION"
ENGINE_VERSION_FILE = REPO_ROOT / "Ortho4XP" / "src" / "O4_Version.py"

PRODUCT_NAME = "XPTerrainBuilder"
COMPANY_NAME = "XPTerrainBuilder"
DESCRIPTION = "X-Plane ortho scenery builder"
# GPL v3 for the engine this exe IS on Windows (LICENSING.md, RELEASES-PLAN §G).
LEGAL_COPYRIGHT = "GPL v3 (engine) / MIT (app) — see LICENSING.md"

TRIPLE_RE = re.compile(r"[0-9]+\.[0-9]+\.[0-9]+")


def read_triple(path: Path) -> str:
    """First MAJOR.MINOR.BUILD in the file, or "" — the shell script's rule."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    match = TRIPLE_RE.search(text)
    return match.group(0) if match else ""


def read_sha() -> str:
    sha = os.environ.get("GITHUB_SHA", "")
    if sha:
        return sha
    try:
        return subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "dev"


def version_tuple(triple: str) -> tuple:
    if not triple:
        return (0, 0, 0, 0)
    parts = [int(p) for p in triple.split(".")]
    return tuple(parts + [0])


def render(app: str, engine: str, sha: str, exe_name: str) -> str:
    vers = version_tuple(app)
    comments = (f"engine {engine or 'dev'} · commit {sha}"
                if sha else f"engine {engine or 'dev'}")
    fields = [
        ("CompanyName", COMPANY_NAME),
        ("FileDescription", DESCRIPTION),
        ("FileVersion", app or "0.0.0"),
        ("InternalName", PRODUCT_NAME),
        ("LegalCopyright", LEGAL_COPYRIGHT),
        ("OriginalFilename", exe_name),
        ("ProductName", PRODUCT_NAME),
        ("ProductVersion", app or "0.0.0"),
        ("Comments", comments),
    ]
    strings = ",\n".join(
        "          StringStruct('%s', %r)" % (key, value) for key, value in fields
    )
    # 040904B0 = US English, Unicode; the VarFileInfo pair must agree with it.
    return (
        "# Generated by scripts/make_version_resource.py — do not edit.\n"
        "VSVersionInfo(\n"
        "  ffi=FixedFileInfo(\n"
        f"    filevers={vers},\n"
        f"    prodvers={vers},\n"
        "    mask=0x3f,\n"
        "    flags=0x0,\n"
        "    OS=0x40004,\n"
        "    fileType=0x1,\n"
        "    subtype=0x0,\n"
        "    date=(0, 0)\n"
        "  ),\n"
        "  kids=[\n"
        "    StringFileInfo(\n"
        "      [\n"
        "      StringTable(\n"
        "        '040904B0',\n"
        "        [\n"
        f"{strings}\n"
        "        ])\n"
        "      ]),\n"
        "    VarFileInfo([VarStruct('Translation', [1033, 1200])])\n"
        "  ]\n"
        ")\n"
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("out", help="version-info file PyInstaller will read")
    parser.add_argument("--exe-name", default="XPTerrainBuilder.exe",
                        help="OriginalFilename (the shipped exe name)")
    args = parser.parse_args(argv)

    app = read_triple(APP_VERSION_FILE)
    engine = read_triple(ENGINE_VERSION_FILE)
    if not app:
        print("NOTICE: no app version tracked at "
              f"{APP_VERSION_FILE} — emitting 0.0.0.0.", file=sys.stderr)
    text = render(app, engine, read_sha(), args.exe_name)
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"version resource -> {args.out} "
          f"(app {app or '0.0.0'}, engine {engine or 'dev'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
