#!/usr/bin/env bash
# THE LINUX APPIMAGE (RELEASES-PLAN §D2).
#
# A single double-clickable file, built from the SAME staged tree the
# tar.gz is made from, so the license payload and VERSION.txt of
# RELEASES-PLAN §G are carried by both artifacts by construction rather
# than by two lists that can drift.
#
# Usage:
#   scripts/make_appimage.sh <staged-dir> <out.AppImage> <icon-png> [appimagetool]
#
#   <staged-dir>    the branded frozen onedir (contains the executable
#                   XPTerrainBuilder plus LICENSE, LICENSING.md,
#                   THIRD-PARTY-NOTICES.txt, gpl.txt, copyright.txt,
#                   VERSION.txt)
#   <out.AppImage>  the file to write
#   <icon-png>      the 256px icon (scripts/make_icon.py output)
#   [appimagetool]  the appimagetool AppImage; default $APPIMAGETOOL.  The
#                   caller downloads it by exact URL and verifies its
#                   sha256 (.github/workflows/release.yml) — this script
#                   never downloads anything.
#
# AppDir layout (the AppImage spec's, plus what desktop environments read):
#
#   AppRun                                            -> execs the binary
#   xpterrainbuilder.desktop                          (root copy: required)
#   xpterrainbuilder.png                              (root copy: required)
#   usr/share/applications/xpterrainbuilder.desktop
#   usr/share/icons/hicolor/256x256/apps/xpterrainbuilder.png
#   usr/bin/<the whole staged tree>
#   LICENSE, LICENSING.md, THIRD-PARTY-NOTICES.txt, gpl.txt,
#   copyright.txt, VERSION.txt                        (§G, at the root)
#
# PyInstaller onedir, never onefile (LGPL v3 / RELEASES-PLAN §G): the Qt
# libraries stay separate relinkable files inside the AppImage's squashfs.
#
# appimagetool runs with --appimage-extract-and-run: the ubuntu-22.04
# runner has no usable FUSE, and without it appimagetool cannot even
# mount itself.
#
# bash, not zsh: this runs on the Linux release runner.
set -euo pipefail

STAGED="${1:?usage: make_appimage.sh <staged-dir> <out.AppImage> <icon-png> [appimagetool]}"
OUT="${2:?usage: make_appimage.sh <staged-dir> <out.AppImage> <icon-png> [appimagetool]}"
ICON="${3:?usage: make_appimage.sh <staged-dir> <out.AppImage> <icon-png> [appimagetool]}"
TOOL="${4:-${APPIMAGETOOL:-}}"

APP_NAME=XPTerrainBuilder
ICON_NAME=xpterrainbuilder

[ -d "$STAGED" ] || { echo "ERROR: no staged dir at $STAGED" >&2; exit 1; }
[ -x "$STAGED/$APP_NAME" ] || {
  echo "ERROR: no executable $STAGED/$APP_NAME — the brand step renames" \
       "the frozen Ortho4XP_Qt binary before this runs." >&2
  exit 1; }
[ -f "$ICON" ] || { echo "ERROR: no icon at $ICON" >&2; exit 1; }
[ -n "$TOOL" ] && [ -f "$TOOL" ] || {
  echo "ERROR: no appimagetool (\$APPIMAGETOOL or 4th argument)" >&2
  exit 1; }

WORK="$(cd "$(dirname "$OUT")" && pwd)"
OUT="$WORK/$(basename "$OUT")"
APPDIR="$WORK/${APP_NAME}.AppDir"
rm -rf "$APPDIR"
mkdir -p "$APPDIR/usr/bin" \
         "$APPDIR/usr/share/applications" \
         "$APPDIR/usr/share/icons/hicolor/256x256/apps"

cp -a "$STAGED/." "$APPDIR/usr/bin/"

# The license payload and the version triple at the AppDir root, where a
# user who runs `--appimage-extract` finds them (RELEASES-PLAN §G).  The
# staged tree already carries them; this is the same files, one level up.
for f in LICENSE LICENSING.md THIRD-PARTY-NOTICES.txt gpl.txt \
         copyright.txt VERSION.txt; do
  if [ -f "$STAGED/$f" ]; then
    cp "$STAGED/$f" "$APPDIR/$f"
  else
    echo "ERROR: $f missing from the staged tree — RELEASES-PLAN §G" \
         "requires it in every artifact root." >&2
    exit 1
  fi
done

# AppRun: no `cd`.  The engine resolves relative paths from the caller's
# working directory, and check_frozen_tile.py drives this very entry point
# with a temp data root — a cd here would silently change both.
cat > "$APPDIR/AppRun" <<'APPRUN'
#!/bin/sh
# Generated by scripts/make_appimage.sh — the AppImage entry point.
HERE="$(dirname "$(readlink -f "$0")")"
export ORTHO4XP_APPIMAGE=1
exec "$HERE/usr/bin/XPTerrainBuilder" "$@"
APPRUN
chmod +x "$APPDIR/AppRun"

cat > "$APPDIR/usr/share/applications/$ICON_NAME.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=XPTerrainBuilder
GenericName=Ortho scenery builder
Comment=Build X-Plane ortho scenery from imagery and elevation data
Exec=XPTerrainBuilder
Icon=$ICON_NAME
Categories=Utility;
Terminal=false
DESKTOP
cp "$APPDIR/usr/share/applications/$ICON_NAME.desktop" \
   "$APPDIR/$ICON_NAME.desktop"

cp "$ICON" "$APPDIR/usr/share/icons/hicolor/256x256/apps/$ICON_NAME.png"
cp "$ICON" "$APPDIR/$ICON_NAME.png"

echo "AppDir assembled at $APPDIR:"
ls -l "$APPDIR"

chmod +x "$TOOL" || true
# ARCH is not always inferred from a PyInstaller tree; state it.
export ARCH="${ARCH:-x86_64}"
# --no-appstream: we ship no AppStream metainfo, and appimagetool's
# validator is not a release gate (the release gate is the tile build
# below it in the job).
"$TOOL" --appimage-extract-and-run --no-appstream "$APPDIR" "$OUT"

chmod +x "$OUT"
ls -l "$OUT"
echo "AppImage: $OUT"
